channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  # - python=3.7.5
  - python=3.8.10

  - pip=20.1
  - pip:
    # Define pip packages here.
    # https://pypi.org/
    - rpaframework==12.1.1 # https://rpaframework.org/releasenotes.html
    # - openpyxl==3.0.9
    - selenium==4.1.0
    - PyPDF4==1.27.0
